name: success-benchmark
on:
  pull_request:
    paths:
      - '**/*'
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  typescript:
    runs-on: ubuntu-20.04
    name: Benchmark TypeScript Types Performance
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: TypeScript benchmark result
        run: node bin -f 17/10000 18 29 32 -b main -g -t --colors
